<nav><a href="<?=$_SERVER['REQUEST_URI']?>Home">Accueil</a><br> <a href="<?= $_SERVER['REQUEST_URI'] ?>Register">S'inscrire</a></nav>
<h2>Login</h2>
<form class="login-form" action="Login" method="post">
    <label for="name">Identifiant</label>
    <input id="name" type="text" name="name">
    <label for="password">Mot de passe</label>
    <input id="password" type="password" name="password">
    <input type="submit" value="Se connecter">
</form>