<nav><a href="<?=$_SERVER['REQUEST_URI']?>Home">Accueil</a><br> <a href="<?= $_SERVER['REQUEST_URI'] ?>Login">Se connecter</a></nav>
<h2>Inscription</h2>
<form class="register-form" action="Register" method="post">
    <label for="name">Identifiant</label>
    <input id="name" type="text" name="name">
    <label for="password">Mot de passe</label>
    <input id="password" type="password" name="password">
    <input type="submit" value="S'inscrire">
</form>