<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Managers\\' => array($baseDir . '/Models/Managers'),
    'LightUp\\' => array($baseDir . '/Framework/LightUp'),
    'Exceptions\\' => array($baseDir . '/Framework/Execeptions'),
    'Entities\\' => array($baseDir . '/Models/Entities'),
    'Controllers\\' => array($baseDir . '/Controllers'),
    'Config\\' => array($baseDir . '/Config'),
);
