<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit3d2bbb841b91e0cee2139813ac30a023
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'Managers\\' => 9,
        ),
        'L' => 
        array (
            'LightUp\\' => 8,
        ),
        'E' => 
        array (
            'Exceptions\\' => 11,
            'Entities\\' => 9,
        ),
        'C' => 
        array (
            'Controllers\\' => 12,
            'Config\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Managers\\' => 
        array (
            0 => __DIR__ . '/../..' . '/Models/Managers',
        ),
        'LightUp\\' => 
        array (
            0 => __DIR__ . '/../..' . '/Framework/LightUp',
        ),
        'Exceptions\\' => 
        array (
            0 => __DIR__ . '/../..' . '/Framework/Execeptions',
        ),
        'Entities\\' => 
        array (
            0 => __DIR__ . '/../..' . '/Models/Entities',
        ),
        'Controllers\\' => 
        array (
            0 => __DIR__ . '/../..' . '/Controllers',
        ),
        'Config\\' => 
        array (
            0 => __DIR__ . '/../..' . '/Config',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit3d2bbb841b91e0cee2139813ac30a023::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit3d2bbb841b91e0cee2139813ac30a023::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit3d2bbb841b91e0cee2139813ac30a023::$classMap;

        }, null, ClassLoader::class);
    }
}
